@echo off

xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\2.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\3.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\4.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\5.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\6.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\7.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\8.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\9.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\10.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\11.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\12.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\13.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\14.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\15.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\16.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\17.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\18.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\19.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\20.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\21.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\22.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\23.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\24.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\25.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\26.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\27.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\28.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\29.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\30.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\31.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\32.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\33.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\34.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\35.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\36.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\37.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\38.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\39.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\40.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\41.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\42.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\43.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\44.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\45.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\46.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\47.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\48.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\49.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\50.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\51.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\52.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\53.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\54.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\55.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\56.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\57.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\58.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\59.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\60.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\61.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\62.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\63.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\64.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\65.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\66.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\67.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\68.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\69.js/y
xcopy C:\Users\student\Desktop\8119\Assignment\JavaScript\1.js C:\Users\student\Desktop\8119\Assignment\JavaScript\70.js/y
