@echo off

xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\2.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\3.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\4.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\5.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\6.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\7.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\8.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\9.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\10.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\11.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\12.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\13.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\14.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\15.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\16.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\17.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\18.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\19.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\20.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\21.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\22.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\23.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\24.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\25.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\26.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\27.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\28.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\29.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\30.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\31.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\32.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\33.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\34.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\35.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\36.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\37.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\38.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\39.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\40.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\41.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\42.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\43.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\44.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\45.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\46.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\47.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\48.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\49.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\50.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\51.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\52.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\53.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\54.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\55.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\56.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\57.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\58.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\59.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\60.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\61.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\62.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\63.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\64.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\65.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\66.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\67.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\68.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\69.html/y
xcopy C:\Users\student\Desktop\8119\Assignment\Html\1.html C:\Users\student\Desktop\8119\Assignment\Html\70.html/y
